// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbmylwaarihscalukxef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhibXlsd2Fhcmloc2NhbHVreGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Mzg5NDcsImV4cCI6MjA3NDAxNDk0N30.E01aSJBh0BnTM0MgaKu2M2oi3gcMr_tQ4XzrnfQxYes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});